### ISSUE TITLE
Cannot open *_Delta files from Windows Docker image layers

### ISSUE THREAD

**Issue by JonoYang** [williballenthin/python-registry#102]
I am trying to use `python-registry` to open the file `System_Delta` from a layer of a Windows docker container. I've obtained the container by running `docker pull python:windowsservercore-1809`. I've also attached the file `System_Delta`. From what I understand, the `System_Delta` stores changes to a registry for a layer of a Docker container. This site seems to explain the concept: https://dfir.ru/2020/08/15/containerized-registry-hives-in-windows/

When I try loading `System_Delta` into `Registry.Registry()`, I get the following error:

```
>>> reg_systemdelta = Registry.Registry("System_Delta")
>>> with open("/home/jono/python-systemdelta-keys.txt", "w") as f:
...     rec(reg_systemdelta.root(), f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 2, in rec
  File "/home/jono/nexb/src/scancode.io/lib/python3.6/site-packages/Registry/Registry.py", line 279, in path
    return self._nkrecord.path()
  File "/home/jono/nexb/src/scancode.io/lib/python3.6/site-packages/Registry/RegistryParse.py", line 1553, in path
    while p.has_parent_key():
  File "/home/jono/nexb/src/scancode.io/lib/python3.6/site-packages/Registry/RegistryParse.py", line 1576, in has_parent_key
    self.parent_key()
  File "/home/jono/nexb/src/scancode.io/lib/python3.6/site-packages/Registry/RegistryParse.py", line 1587, in parent_key
    d = HBINCell(self._buf, offset, self.parent())
  File "/home/jono/nexb/src/scancode.io/lib/python3.6/site-packages/Registry/RegistryParse.py", line 561, in __init__
    self._size = self.unpack_int(0x0)
  File "/home/jono/nexb/src/scancode.io/lib/python3.6/site-packages/Registry/RegistryParse.py", line 272, in unpack_int
    return struct.unpack_from(str("<i"), self._buf, self._offset + offset)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes
```

I am able to read this file using `registry-dump` from `regipy`.

[System_Delta.tar.gz](https://github.com/williballenthin/python-registry/files/6665762/System_Delta.tar.gz)

**Comment by williballenthin** [comment]
you need to pass a file-like object to the `Registry.Registry` constructor, something like:

![image](https://user-images.githubusercontent.com/156560/122305822-ad386c00-cec4-11eb-90e5-54e9ec5cf48a.png)
