### ISSUE TITLE
reg_export exception "must be str, not bytes" with python 3.4

### ISSUE THREAD

**Issue by NiKiZe** [williballenthin/python-registry#37]
```
$ python3.4 samples/reg_export.py BCD BCD System
Traceback (most recent call last):
  File "samples/reg_export.py", line 158, in <module>
    main(*sys.argv[1:])
  File "samples/reg_export.py", line 149, in main
    sys.stdout.write(reg_format_header())
TypeError: must be str, not bytes
```

The reason for using python 3.4 was becuase of enum import error with python 2.7
```
  File "Registry/Registry.py", line 23, in <module>
    from enum import Enum
ImportError: No module named enum
```

Will try to fix the first issue and make a PR.

**Comment by NiKiZe** [comment]
`sys.stdout.buffer.write()` works in 3.4 but not in 2.7
Safe but not-so-beautiful way is to redeclare stdout:

```diff
diff --git a/samples/reg_export.py b/samples/reg_export.py
index 62df98f..0042cfa 100644
--- a/samples/reg_export.py
+++ b/samples/reg_export.py
@@ -22,6 +22,9 @@ from __future__ import unicode_literals
 import sys
 from Registry import Registry
 
+stdout = sys.stdout
+if hasattr(stdout, 'buffer'):
+    stdout = stdout.buffer
 
 def usage():
     return "  USAGE:\n\t%s <Windows Registry file> <Hive prefix> <Registry key path> [<Registry Value>]" % sys.argv[0]
@@ -146,8 +149,8 @@ def main(hive, prefix, keyname, *valuenames):
     else:
         values = [v for v in key.values()]
 
-    sys.stdout.write(reg_format_header())
-    sys.stdout.write(reg_format_key_values(registry, prefix, key, values))
+    stdout.write(reg_format_header())
+    stdout.write(reg_format_key_values(registry, prefix, key, values))
 
 
 if __name__ == '__main__':
```

**Comment by williballenthin** [comment]
Ah, yes, I'm still gaining familiarity with python3. This fix looks good (no need to over-engineer it yet :-) ). Would you open a PR with this fix?

**Comment by NiKiZe** [comment]
I will check if there is any of the other files that needs this as well and create a PR
