### ISSUE TITLE
Error parsing large_data keys

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-registry#7]
xp $ python ~/projects/python-registry/samples/findkey.py NTUSER.DAT.copy0 "upx305w"
Traceback (most recent call last):
  File "/home/willi/projects/python-registry/samples/findkey.py", line 24, in <module>
    rec(reg.root(), 0, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 17, in rec
    rec(subkey, depth + 1, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 17, in rec
    rec(subkey, depth + 1, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 17, in rec
    rec(subkey, depth + 1, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 17, in rec
    rec(subkey, depth + 1, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 17, in rec
    rec(subkey, depth + 1, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 17, in rec
    rec(subkey, depth + 1, needle)
  File "/home/willi/projects/python-registry/samples/findkey.py", line 11, in rec
    if needle in str(value.value()):
  File "/usr/local/lib/python2.7/dist-packages/Registry/Registry.py", line 139, in value
    return self._vkrecord.data()
  File "/usr/local/lib/python2.7/dist-packages/Registry/RegistryParse.py", line 697, in data
    return db.large_data(data_length)
AttributeError: 'DataRecord' object has no attribute 'large_data'

**Comment by msuhanov** [comment]
What is the minor version of the NTUSER.DAT hive? There was no support for the DB records in the version 1.3, so the bug fix applied may result in different parsing results between Windows and python-registry (when data starts with the 'db' string).

**Comment by williballenthin** [comment]
i suspect i dont have this hive handy anymore, since i've been through a few laptops since when i reported this issue. sorry.
