### ISSUE TITLE
AttributeError: 'VKRecord' object has no attribute 'data' when reading SOFTWARE registry

### ISSUE THREAD

**Issue by passwordleak** [williballenthin/python-registry#85]
The SOFTWARE registry is in C:\Windows\System32\config\SOFTWARE and contains the HKLM:\SOFTWARE registry keys. I am running this on a linux host with a windows partition mounted. 

source code:
```
import sys
from Registry import Registry
reg= Registry.Registry('/mnt/mount/Windows/System32/config/SOFTWARE')
key = reg.open("Microsoft\\Windows NT\\CurrentVersion")
for value in [v for v in key.values() \
                   if v.value_type() == Registry.RegSZ or \
                      v.value_type() == Registry.RegExpandSZ]:
    print("%s: %s" % (value.name(), value.value()))
```
error:
```
Traceback (most recent call last):
  File "[redacted]/test.py", line 8, in <module>
    print("%s: %s" % (value.name(), value.value()))
  File "[redacted]/Registry.py", line 160, in value
    return self._vkrecord.data()
AttributeError: 'VKRecord' object has no attribute 'data'
```
The keys have names and types, but not values.

**Comment by passwordleak** [comment]
EDIT: Using the latest version seemed to fix it. Not sure why this even happened. Maybe some IDE stuff.
